# This code was generated by Google Gemini.
# Prompt: "Create a basic Flask app stub."

from flask import Flask, jsonify, request
from models import Expense
from patterns import TransactionManager, BudgetAlert

app = Flask(__name__)

# Initialize our system
manager = TransactionManager()
alert_system = BudgetAlert()
manager.register_observer(alert_system)

@app.route('/')
def home():
    return "CATT Backend is running!"

@app.route('/api/add_expense', methods=['POST'])
def add_expense():
    # This is a stub endpoint
    data = request.json
    print(f"Received data: {data}")
    return jsonify({"status": "success", "message": "Expense received"}), 201

if __name__ == '__main__':
    app.run(debug=True)