# This code was generated by Google Gemini.
# Prompt: "Create simple Python dataclasses for User and Expense."

from dataclasses import dataclass
from datetime import datetime

@dataclass
class Expense:
    amount: float
    category: str
    date: str
    note: str = ""

    def __post_init__(self):
        if self.amount < 0:
            raise ValueError("Expense amount cannot be negative")
        
class User:
    def __init__(self, email, password):
        if "@" not in email or "." not in email:
            raise ValueError("Invalid email format")
        self.email = email
        self.password = password
    
    def login(self, email, password):
        # Stub for login logic
        print(f"Attempting login for {email}")
        return self.email == email and self.password == password

    def create_account(self, email, password):
        # Stub for account creation
        print(f"Creating account for {email}")
        return True