# This code was generated by Google Gemini.
# Prompt: "Generate the Observer pattern structure for a transaction manager."

from abc import ABC, abstractmethod

# The Observer Interface
class IObserver(ABC):
    @abstractmethod
    def update(self, expense):
        pass

# The Subject (Transaction Manager)
class TransactionManager:
    def __init__(self):
        self._observers = []
        self._expenses = []

    def register_observer(self, observer: IObserver):
        self._observers.append(observer)

    def remove_observer(self, observer: IObserver):
        self._observers.remove(observer)

    def notify_observers(self, expense):
        for observer in self._observers:
            observer.update(expense)

    def add_expense(self, expense):
        print(f"Backend: Adding expense for ${expense.amount}")
        self._expenses.append(expense)
        self.notify_observers(expense)

# Concrete Observer: Dashboard Notification
class BudgetAlert(IObserver):
    def update(self, expense):
        # Logic to check if budget is exceeded
        print(f"Alert System: Checking if ${expense.amount} puts {expense.category} over budget...")