# This code was generated by Google Gemini.
# Prompt: "Using Python's unittest, generate unit tests for a User class (login, create_account), 
# an Expense dataclass, and an integration test for an Observer pattern TransactionManager 
# that updates a BudgetAlert observer."

import unittest
from models import User, Expense
from patterns import TransactionManager, BudgetAlert, IObserver

# --- Unit Tests ---

class TestUserModel(unittest.TestCase):
    def setUp(self):
        self.user = User("test@vt.edu", "password123")

    def test_create_account(self):
        # Testing the create_account stub from PM4
        result = self.user.create_account("new@vt.edu", "pass")
        self.assertTrue(result, "Account creation should return True")

    def test_login_success(self):
        # Testing the login stub
        self.assertTrue(self.user.login("test@vt.edu", "password123"))

    def test_login_failure(self):
        # Testing login failure logic
        self.assertFalse(self.user.login("test@vt.edu", "wrongpass"))

class TestTransactionManager(unittest.TestCase):
    def setUp(self):
        self.manager = TransactionManager()

    def test_add_expense_list(self):
        # Unit test to ensure expense is added to the internal list
        expense = Expense(10.0, "Food", "2025-10-10")
        self.manager.add_expense(expense)
        self.assertEqual(len(self.manager._expenses), 1)

# --- Integration Test ---

class TestObserverIntegration(unittest.TestCase):
    def test_budget_alert_trigger(self):
        """
        Integration Test: Verifies that adding an expense to the Manager
        successfully triggers the update method in the Observer.
        """
        # 1. Setup the Subject (Manager)
        manager = TransactionManager()
        
        # 2. Setup a Mock Observer to spy on the system
        class MockObserver(IObserver):
            def __init__(self):
                self.notified = False
                self.last_expense = None
            
            def update(self, expense):
                self.notified = True
                self.last_expense = expense
        
        # 3. Register the observer
        observer = MockObserver()
        manager.register_observer(observer)
        
        # 4. Action: Add an expense
        expense = Expense(100.0, "Social", "2025-12-01")
        manager.add_expense(expense)
        
        # 5. Assert: Check if the observer was actually called (Integration success)
        self.assertTrue(observer.notified, "Observer should have been notified")
        self.assertEqual(observer.last_expense.category, "Social", "Observer received wrong data")

if __name__ == '__main__':
    unittest.main()